### ISSUE TITLE
UX changes for social media sharing links

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry.io#564]
~~Allow folks to share lbry.io/news articles on social media with a button click. Twitter, Facebook, etc.~~ Social media links exist but are at the very bottom of the news article. Change this to make sharing links more obvious and that they are for sharing the article. I thought they were links to LBRY's social media accounts and never clicked them.

**Comment by tzarebczan** [comment]
@ykris45 didn't you work on a mockup for this?

**Comment by ykris45** [comment]
@tzarebczan not yet because render process of loaded all markdown on my computer look out of memory

**Comment by heymattsokol** [comment]
At risk of being too simple, I think there's a very simple UX answer to this. 

Using imgur today because Spee.ch is slow with the hard fork -- https://imgur.com/a/rctD69p

That is my proposed change to the design, with three different fonts to consider. On top of that, I propose that we include the share buttons on top AND bottom of the article, as that would cover both use cases (i.e. "This looks cool, I want to share immediately" and "I just finished reading, now i want to share"

I can't self-assign this issue I don't think, can someone else assign it to me? Or don't hesitate to tell me if I am doing this completely wrong, as this is my first attempt at contributing on GitHub o_o

**Comment by alyssaoc** [comment]
@NetOperatorWibby Can you take a look at this solution and see what you think?

**Comment by NetOperatorWibby** [comment]
@heymattsokol The first option works.

**Comment by alyssaoc** [comment]
closing will consider this as part of a larger redesign
