### ISSUE TITLE
New tag comments-waitlist needs description and pretty name

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry.io#873]
The email management page needs to have a description added for a few tags, or the tags not not be made public. 

<img width="792" alt="screen shot 2018-11-07 at 10 39 16 pm" src="https://user-images.githubusercontent.com/3402064/48176448-089e2880-e2de-11e8-8e1d-9f21d4053fb9.png">

**Comment by tzarebczan** [comment]
Didn't we agree new tags won't be public? I'll make sure this is filed. But I'm pretty sure comments-waitlist was set to non public. 

@kauffj, do we want users to be able to unsub from the comments waitlist?

**Comment by tiger5226** [comment]
Maybe, but I did not make any changes. The real solution is to adjust the user interface to allow people to set these fields. I created an PR for our APIs to make sure the default behavior is to make new tags not public and not user addable.

**Comment by tiger5226** [comment]
>But I'm pretty sure comments-waitlist was set to non public.

It was, but I made it public because @seanyesmunt needs this tag manageable from the edit API. In order for it to be manageable it needs to be a public tag.

**Comment by kauffj** [comment]
I just (crudely) made it stop rendering tags without descriptions (https://github.com/lbryio/lbry.io/commit/bc1dbacf75b2b63dffe99eaa2ddbd975656f1400).

@lbryio/growth members, public tags will no longer show up on editing email unless descriptions have explicitly been set in the website codebase

@tiger5226 could you file a tag in internal-apis to make relevant tag and api-forms changes so that this can stop being hard-coded in lbry.io?

**Comment by tiger5226** [comment]
Will do

**Comment by kauffj** [comment]
I'm closing this, since I don't think we actually want this tag visible.
